ai_blog_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog_generator.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, reverse_lazy
from . import views

app_name = 'reviews'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('sign_up/', views.SignUpUser.as_view(), name='sign_up'),
    path('verify_email/<uidb64>/<str:token>/', views.verify_email, name='verify_email'),
    path('check_email/', views.check_email, name='check_email'),
    path('password-reset/',
         PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                   email_template_name='users/password_reset_email.html',
                                   success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

users/models.py
from django.db import models

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username', required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'id': 'UsernameForm',
                                                             'placeholder': 'Enter your username'}))
    password = forms.CharField(label='Пароль', required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'id': 'PasswordField',
                                                                 'placeholder': 'Enter your password'}))
    captcha = ReCaptchaField(label='', widget=ReCaptchaV3())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class SignUpUserLogin(UserCreationForm):
    username = forms.CharField(label='Username', required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'id': 'UsernameForm',
                                                             'placeholder': 'Enter your username'}))
    email = forms.EmailField(label='E-mail', required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'id': 'EmailForm',
                                                            'placeholder': 'Enter your email'}))
    password1 = forms.CharField(label='Пароль', required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'id': 'PasswordField',
                                                                  'placeholder': 'Enter your password'}))
    password2 = forms.CharField(label='Подтвердите пароль', required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'id': 'ConfirmPasswordField',
                                                                  'placeholder': 'Confirm your password'}))
    captcha = ReCaptchaField(label='', widget=ReCaptchaV3())

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
    def cleaned_password2(self):
        cd = self.cleaned_data
        if cd['password1'] == cd['password2']:
            raise forms.ValidationError('Passwords don\'t match!')
        return cd['password1']

    def clean_email(self):
        cd = self.cleaned_data
        if get_user_model().objects.filter(email=cd['email']).exists():
            raise forms.ValidationError('E-mail уже зарегистрирован в системе!')
        return cd['email']


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'id': 'UsernameForm',
                                                             'placeholder': 'Enter your username'}))
    email = forms.EmailField(disabled=True, label='E-mail',
                             widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'id': 'EmailForm',
                                                            'placeholder': 'Enter your email'}))
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый Пароль', required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'id': 'PasswordField',
                                                                  'placeholder': 'Enter your old password'}))
    new_password1 = forms.CharField(label='Новый Пароль', required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'id': 'PasswordField',
                                                                  'placeholder': 'Enter your new password'}))
    new_password2 = forms.CharField(label='Подтвердите новый пароль', required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'id': 'ConfirmPasswordField',
                                                                  'placeholder': 'Confirm your new password'}))

users/views.py
from django.contrib.auth import login, authenticate, logout, get_user_model

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponseRedirect, HttpResponseServerError
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from django.views.generic import CreateView, UpdateView


from .forms import LoginUserForm, SignUpUserLogin, ProfileUserForm, UserPasswordChangeForm
from .tokens import account_activation_token


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Blog Generator'}

    def get_success_url(self):
        return reverse_lazy('home')


class SignUpUser(CreateView):
    form_class = SignUpUserLogin
    template_name = 'users/sign_up.html'
    extra_context = {'title': 'Blog Generator'}

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        message = render_to_string(
            'users/email.html',
            context={
                "domain": current_site.domain,
                "protocol": "http",
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            }
        )

        send_mail(
            'Подтвердите E-mail',
            message,
            'AiBlogGen@yandex.ru',
            [user.email],
            fail_silently=False,
        )


        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:check_email')


def check_email(request):
    return render(request, 'users/check_email.html', context={'title': 'Blog Generator'})


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Blog Generator'}

    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.request.user.pk])

    def get_object(self, queryset=None):
        return self.request.user

class PasswordChangeView(PasswordChangeView):
    model = get_user_model()
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'



def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('home'))


def verify_email(request, uidb64, token):
    try:
        user_id = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=user_id)
        user.is_active = True
        user.save()

        return render(request, 'users/email_verified.html', context={'title': 'Blog Generator'})

    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        return HttpResponseServerError('<h1>Invalid activation link</h1>')

users/templates/users/check_email.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;"
     onmouseover="this.style.transform = 'scale(1.1)';"
     onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
            <h1>Подтвердите E-mail</h1>

            <p>Чтобы завершить процесс подтверждения адреса электронной почты, пожалуйста, откройте свою почту и найдите сообщение
                от нас. Перейдите по ссылке в письме для подтверждения вашего адреса электронной почты.</p>
    </div>
</div>
{% endblock %}

users/templates/users/email.html
Подтвердите E-mail.
Пожалуйста, нажмите на ссылку ниже, чтобы подтвердить ваш адрес электронной почты:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}
{% endblock %}

users/templates/users/email_verified.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;"
     onmouseover="this.style.transform = 'scale(1.1)';"
     onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
            <h1>E-mail подтвержден</h1>

            <p>Ваш электронный адрес успешно подтвержден. Благодарим вас за регистрацию!
                Теперь вы можете войти в аккаунт</p>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

<!-- Main -->
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.05)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Вход в аккаунт</h2>
        <form method="post">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}" />
          <div class="form-error">{{ form.non_field_errors }}</div>
          {% for field in form %}
            <div class="form-outline mb-4">
              <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</p>
              <div class="form-error">{{ field.errors }}</div>
            </div>
          {% endfor %}
            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Вход</button>
          <div class="text-center">
            <p>Еще не зарегистрирваны? <a href="{% url 'users:sign_up' %}">Регистрация</a></p>
          </div>
          <div class="text-center">
              <!-- Simple link -->
              <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
            </div>
    </div>

        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.1)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h1>Пароль успешно изменен!</h1>

        <p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

<!-- Main -->
<div class="flex-grow container mt-5 mb-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.1)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Изменение пароля</h2>
        <form method="post">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}" />
          <div class="form-error">{{ form.non_field_errors }}</div>
          {% for field in form %}
            <div class="form-outline mb-4">
              <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</p>
              <div class="form-error">{{ field.errors }}</div>
            </div>
          {% endfor %}
            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Изменить пароль</button>
        </form>



  </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.1)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
<a href="{% url 'users:login' %}">входа в систему</a>.</p>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

<!-- Main -->
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.1)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Введите новый пароль</h2>
        <form method="post">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}" />
          <div class="form-error">{{ form.non_field_errors }}</div>
          {% for field in form %}
            <div class="form-outline mb-4">
              <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</p>
              <div class="form-error">{{ field.errors }}</div>
            </div>
          {% endfor %}
            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Save</button>
    </div>

        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

<!-- Main -->
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.1)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Успешный сброс пароля</h2>

        <p>Мы отправили вам по электронной почте инструкции по установке пароля, если у вас есть учетная запись, указав указанный вами адрес электронной почты. Вы должны получить их в ближайшее время.</p>

        <p>Если вы не получили электронное письмо, пожалуйста, убедитесь, что вы указали адрес, на который указывали при регистрации, и проверьте папку со спамом.</p>

    </div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

{% load custom_filters %}

<!-- Main -->
<div class="flex-grow container mt-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.1)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Сбросьте пароль с помощью электронной Почты</h2>
        <form method="post">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}" />
          <div class="form-error">{{ form.non_field_errors }}</div>
          {% for field in form %}
            <div class="form-outline mb-4">
                <p>
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|set_placeholder:"Enter your E-mail"|add_class:"form-control" }}
                </p>
                <div class="form-error">{{ field.errors }}</div>
            </div>

            {% endfor %}
            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Сбросить пароль</button>

        </form>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

<!-- Main -->
<div class="flex-grow container mt-5 mb-4 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.05)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Профиль</h2>
        <form method="post">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}" />
          <div class="form-error">{{ form.non_field_errors }}</div>
          {% for field in form %}
            <div class="form-outline mb-4">
              <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</p>
              <div class="form-error">{{ field.errors }}</div>
            </div>
          {% endfor %}

        </form>

        <a href="{% url 'users:password_change' %}" class="text-black hover:underline"><p class="fw-normal">Сменить пароль</p></a>
        <a href="{% url 'users:logout' %}" class="text-black hover:underline"><p class="fw-normal">Выйти</p></a>

  </div>

</div>
<div class="flex-grow container mt-3 mb-2 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.05)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <a class="text-decoration-none text-dark" href="{% url 'posts' %}"><h2>История статей</h2></a>
    </div>
</div>
{% endblock %}

users/templates/users/sign_up.html
{% extends 'ai_blog_app/templates/base.html' %}
{% block content %}

<!-- Main -->
<div class="flex-grow container mt-5 mb-5 w-50" style="transition: transform 0.3s, box-shadow 0.3s;" onmouseover="this.style.transform = 'scale(1.05)';" onmouseout="this.style.transform = 'scale(1)'; this.style.boxShadow = 'none';">
    <div class="p-4 text-dark bg-white rounded-3 shadow">
        <h2>Регистрация</h2>
        <form method="post">
          {% csrf_token %}

          <input type="hidden" name="next" value="{{ next }}" />
          <div class="form-error">{{ form.non_field_errors }}</div>
          {% for field in form %}
            <div class="form-outline mb-4">
              <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</p>
              <div class="form-error">{{ field.errors }}</div>
            </div>
          {% endfor %}

          <!-- Submit button -->
          <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Зарегистрироваться</button>

          <!-- Register buttons -->
          <div class="text-center">
            <p>Уже зарегистрированы? <a href="{% url 'users:login' %}">Войти</a></p>
          </div>
        </form>
  </div>
</div>
{% endblock %}