ai_blog_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog_generator.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, reverse_lazy
from . import views

app_name = 'reviews'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('sign_up/', views.SignUpUser.as_view(), name='sign_up'),
    path('verify_email/<uidb64>/<str:token>/', views.verify_email, name='verify_email'),
    path('check_email/', views.check_email, name='check_email'),
    path('password-reset/',
         PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                   email_template_name='users/password_reset_email.html',
                                   success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

ai_blog_app/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <link type="text/css" rel="stylesheet" href="{% static 'blog_generator/css/style.css' %}">
  <link href="{% static 'blog_generator/css/bootstrap.min.css' %}"
        rel="stylesheet" crossorigin="anonymous">
</head>

<body class="bg-light">

  <header class="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-9">
            <h1><a class="fw-normal text-decoration-none text-white" href="{% url 'home' %}">{{ title }}</a></h1>
        </div>
        <div class="col-3 d-flex flex-row-reverse">
            {% if user.is_authenticated %}
                 <div class="p-2 bd-highlight">
                     <a href="{% url 'users:profile' %}"
                                                  class="font-monospace
                                                   text-decoration-none text-white hover:underline">
                         {{ user.username }}</a></div>
            {% else %}
            <div class="p-2 bd-highlight">
                <p class="text-white hover:underline">
                    <a href="{% url 'users:login' %}" class="text-white hover:underline">Войти</a> |
                    <a href="{% url 'users:sign_up' %}" class="text-white hover:underline">Регистрация</a>
                </p></div>
            {% endif %}
        </div>
      </div>
    </div>
  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer>
  </footer>

<script src="{% static 'blog_generator/js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>